version: '3.8'
services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # Puerto principal de LocalStack
      - "4510-4559:4510-4559"  # Puertos dinámicos
    environment:
      - SERVICES=secretsmanager
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - PERSISTENCE=1
      - HOSTNAME_EXTERNAL=host.docker.internal
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    extra_hosts:
      - "host.docker.internal:host-gateway" 